chore: delete outdated text
International-Data-Spaces-Association/DataspaceConnector pull request #587
Opened 2022-12-08 10:45 UTC by omarsilva1

2022-12-08 11:01 UTC, tmberthold submitted a review, later dismissed

2022-12-08 11:30 UTC, SebastianOpriel requested changes

2022-12-08 11:30 UTC, SebastianOpriel commented on docs/pages/deployment/update.md
>      "website": "https://www.dataspace-connector.io/",
Remove

2022-12-08 11:30 UTC, SebastianOpriel commented on docs/pages/deployment/update.md
>      "email": "support@sovity.de"
Contact@

2022-12-08 11:30 UTC, SebastianOpriel commented on docs/pages/deployment/update.md
> +    "organization": "sovity",
sovity GmbH

2022-12-12 08:05 UTC, omarsilva1 commented on docs/pages/deployment/update.md
> +    "organization": "sovity",
done

2022-12-12 08:45 UTC, tmberthold approved these changes

2022-12-12 10:26 UTC, merged